### ISSUE TITLE
[Bug] Ссылка на Манифест сообщества открывается некорректно

### ISSUE THREAD

**Issue by ksenia-nenasheva** [futurerussia-ch/futurerussia-website#1]
Ссылка на Манифест сообщества открывается некорректно
https://www.futurerussia.ch/contact-8 
Главная страница -> Контакты -> Манифест

Открывается "страница в странице". 
Предполагаю, что должен был быть переход на новую страницу.

<img width="1378" alt="Screenshot 2022-10-01 at 16 44 44" src="https://user-images.githubusercontent.com/5075432/193415044-d5b7b5df-b8ca-4d93-90a9-f44f2c213501.png">

Воспроизводится в Safari и Google Chrome

**Comment by oleg-nenashev** [comment]
Проблема связана с импортом текста. Wix при этом делает Embed страницы вместо подгрузки текста. Надо править

**Comment by oleg-nenashev** [comment]
Я убрал импорт с Гитхаба и заменил текстом
