### ISSUE TITLE
[Bug]: Кнопка "Отправить" в DE версии отображается на русском языке

### ISSUE THREAD

**Issue by ksenia-nenasheva** [futurerussia-ch/futurerussia-website#14]
### Что случилось?

Скриншот:

<img width="837" alt="Screenshot 2022-10-03 at 11 12 01" src="https://user-images.githubusercontent.com/5075432/193547385-25fa5d15-24f2-4740-b4a0-ce563ec9e82d.png">

В EN и FR версиях отображается корректно.

### Используемые браузеры

Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oleg-nenashev** [comment]
Спасибо, поправил
