### ISSUE TITLE
[Bug]: Адреса страниц правильнее делать на английском языке

### ISSUE THREAD

**Issue by ksenia-nenasheva** [futurerussia-ch/futurerussia-website#15]
### Что случилось?

Это скорее баг, чем улучшение.

https://www.futurerussia.ch/помочь
https://www.futurerussia.ch/о-нас
https://www.futurerussia.ch/contact-8

Ссылки лучше делать на английском языке и короче (без "-8" в данном случае)
Так удобнее и проще в случае копирования и публикации. 
Например, если ссылку на какую-то страницу этого сайта захочет опубликовать местная газета.

### Используемые браузеры

Chrome, Safari

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by oleg-nenashev** [comment]
Согласен. Особенности системы

**Comment by oleg-nenashev** [comment]
Все ссылки переименованы, редиректы добавлены
