### ISSUE TITLE
[Bug]: очепятка на франц странице с уставом

### ISSUE THREAD

**Issue by MariaRossen** [futurerussia-ch/futurerussia-website#20]
### Что случилось?

![72960A08-E185-4D32-9BC5-D582E675CC3A](https://user-images.githubusercontent.com/115044490/196035648-e7777de7-5b88-4f79-baf5-c68cabb04465.jpeg)
Всё пропало, шеф!

### Используемые браузеры

Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ksenia-nenasheva** [comment]
Добавлю несколько моментов

https://www.futurerussia.ch/fr/structure
Проблема с отображением текста
`Groupe de contact &quot;Politique&quot;`

Много пробелов перед знаками препинания (перед двоеточиями и точками с запятой).

**Comment by oleg-nenashev** [comment]
Fixed, thanks!
