### ISSUE TITLE
[Bug]: Кнопка "Помочь" дублируется

### ISSUE THREAD

**Issue by ksenia-nenasheva** [futurerussia-ch/futurerussia-website#22]
### Что случилось?

Кнопка "Помочь" дублируется - в правом верхнем углу и с подменю "Сообщество"
Ссылка ведет на одну и ту же страницу.

Я бы удалила одну из них (и изменила бы текст в RU версии на "Помощь сообществу")

<img width="535" alt="Screenshot 2022-10-21 at 10 30 20" src="https://user-images.githubusercontent.com/5075432/197151082-d599ac29-237c-4a0c-83a3-e58433a994ea.png">

### Используемые браузеры

Chrome, Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oleg-nenashev** [comment]
Переименовал кнопку на панели
